# USAGE: conda env create -f environment.yml
name: navex
channels:
- conda-forge
- pytorch
dependencies:
- python=3.8
- pip
- paramiko
- pytorch
- torchvision
- cudatoolkit=11.0
- pytorch-lightning
- pip:
  - pytorch-lightning-bolts
  - opencv-contrib-python
  - adabelief-pytorch==0.2.0
  - -e git://github.com/oknuutti/r2d2.git#egg=r2d2
  - ray
  - ray[tune]
